### ISSUE TITLE
Page setup parameters cannot be set on xltable/worksheets

### ISSUE THREAD

**Issue by stuartjchapman** [fkarb/xltable#8]
The _xlsxwriter_ package has a number of methods that allow a user to tailor the "Page Layout" of an Excel worksheet. Page set-up methods affect the way that a worksheet looks when it is printed. They control features such as paper size, orientation, page headers and margins. 

See http://xlsxwriter.readthedocs.io/page_setup.html for more detail. 

I suggest that these methods are exposed to the _xltable/worksheet_ class and then set as part of its _to_xlsx()_ method.

**Comment by tonyroberts** [comment]
If you create the xltable workbook with no filename, when you call to_xlsx() it will return you the xlsx workbook without saving it. Would that allow you to go back and setup the worksheets before saving?

**Comment by stuartjchapman** [comment]
I did try editing the workbook_obj directly, but the nuance I missed was that the filename was passed to the _to_xlsx()_ call. 

I have now got it working using following steps:
1. call _xltable/workbook.to_xlsx()_ without a filename
2. get the required _xlsxwriter/worksheet_ instance contained in  the _xltable/workbook_'s _workbook_obj.worksheets_objs[?]_ attribute 
3. edit the page_setup parameters directly on the _xlsxwriter/worksheet_ instance, eg _.set_paper(8)_
4. set the filename to the xlsxwriter workbook by _xltable/workbook.workbook_obj.filename_
5. close the xlsxwriter workbook via: _xltable/workbook.workbook_obj.close()_

Thanks for showing me the light. :-)

**Comment by tonyroberts** [comment]
👍
