### ISSUE TITLE
passing dict of CellStyles to header_style or index_style sometimes causes IndexError

### ISSUE THREAD

**Issue by stuartjchapman** [fkarb/xltable#9]
I'm looking at _xltable/worksheet._get_all_styles()_ method. I query whether the following code excerpts reference the right col_name / row_name. 

`                for c in range(col, col + table.width):
                    if isinstance(table.header_style, dict):
                        col_name = table.dataframe.columns[c]
                        style = table.header_style.get(col_name, _get_style(bold=True))`

`                for r in range(row + table.header_height, row + table.height):
                    if isinstance(table.index_style, dict):
                        row_name = table.dataframe.index[r]
                        style = table.index_style.get(row_name, _get_style(bold=True))`

For example, if a table is positioned with top-left cell at (5,10), then the first value for _r_ would be _r=5_ . if the table's dataframe only has 4 rows then index would be [0,3] and therefore row_name = table.dataframe.index[r] would raise an IndexError. Is my thought reasonable?

**Comment by tonyroberts** [comment]
Yes that does look like a bug(s). It looks like it should be ```c - col``` and ```r - row``` when indexing into columns and index respectively. If you make that change does it work?
